<div class="accountcontent">
    <div
        class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-container106">
        <div
            class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-background-border1">
            <div
                class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-container107">
                <div
                    class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-heading1">
                    <span
                        class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-text104">
                        <span>Tài khoản</span>
                    </span>
                </div>
                <div
                    class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-container108">
                    <div
                        class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-container109">
                        <div
                            class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-container110">
                            <span
                                class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-text106">
                                <span>
                                    Nếu bạn đã có tài khoản, đăng nhập tại đây.
                                </span>
                            </span>
                            <div
                                class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-form1">
                                <div
                                    class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-fieldset1">
                                    <div
                                        class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-label1">
                                        <span
                                            class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-text108">
                                            <span>Email:</span>
                                        </span>
                                    </div>
                                    <div
                                        class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-input1">
                                        <div
                                            class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-container111">
                                            <input
                                                class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-text110"
                                                placeholder="Email"
                                            />
                                        </div>
                                    </div>
                                </div>
                                <div
                                    class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-fieldset2">
                                    <div
                                        class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-label2">
                                        <span
                                            class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-text112">
                                            <span>Mật khẩu:</span>
                                        </span>
                                    </div>
                                    <div
                                        class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-input2">
                                        <div
                                            class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-container112">
                                            <input
                                                class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-text114"
                                                placeholder="Mật khẩu"
                                                type="password"
                                            />
                                        </div>
                                    </div>
                                </div>
                                <div
                                    class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-container113">
                                    <button

                                        class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-input3">
                                        <!-- LOGIN FUNCTION -->
                                        Đăng nhập</button>
                                    <div
                                        class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-link12">
                                        <a href="index.php?quanly=register"
                                            class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-text116">
                                            <span>Đăng ký</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div
                        class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-container114">
                        <div
                            class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-container115">
                            <span
                                class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-text118">
                                <span>
                                    Bạn quên mật khẩu? Nhập địa chỉ email để lấy lại mật
                                    khẩu qua email. <span style="color : red">( TÍNH NĂNG ĐANG BẢO TRÌ )</span>
                                </span>
                            </span>
                            <div
                                class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-form2">
                                <div
                                    class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-container116">
                                    <div
                                        class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-fieldset3">
                                        <div
                                            class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-label3">
                                            <span
                                                class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-text120">
                                                <span>Email:</span>
                                            </span>
                                        </div>
                                        <div
                                            class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-input4">
                                            <div
                                                class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-container117">
                                                <span
                                                    class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-text122">
                                                    <span>Email</span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div
                                    class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-container118">
                                    <button
                                        style="cursor:pointer"
                                        class="nhenvnbyhtmltodesign-fre-eversion09092024214426gmt7-input5">Lấy lại mật khẩu</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
    include("pages/main/clb.php");
    ?>
</div>